services:
  orantio-cache:
    image: redis:6.2.16
    container_name: orantio-cache
    restart: always
    networks:
      - orantio
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - cache:/data

  orantio-api:
    container_name: orantio-api
    build:
      context: .
      target: api
    networks:
      - orantio
#      - elastic
    env_file:
      - api/config.env
    environment:
      - REDIS_HOST=orantio-cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    ports:
      - "4001:4001"
    depends_on:
      - orantio-cache
    volumes:
      - ./logs/:/logs/

  orantio-apollo:
    container_name: orantio-apollo
    build:
      context: .
      target: apollo
    networks:
      - orantio
      - notification
#      - elastic
    env_file:
      - apollo/config.env
    ports:
      - "4000:4000"
    volumes:
      - ./logs/:/logs/

  orantio-nginx:
    container_name: orantio-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
      - ./entrypoint.sh:/docker-entrypoint.d/entrypoint.sh
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "80:80"
    networks:
      - orantio
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    entrypoint: ["/bin/sh", "-c"]
    command:
      [
        "/wait-for-it.sh orantio-api:4001 orantio-apollo:4000 -- /docker-entrypoint.d/entrypoint.sh",
      ]
    depends_on:
      - orantio-api
      - orantio-apollo
      - orantio-cache

  orantio-cronjob:
    container_name: orantio-cronjob
    build:
      context: .
      target: cronjob
    networks:
      - orantio
    depends_on:
      - orantio-api
      - orantio-apollo
      - orantio-cache

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.2
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/logs/
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    depends_on:
      - orantio-api
      - orantio-apollo
    networks:
      - orantio
#      - elastic

networks:
  orantio:
  notification:
    external: true
#  elastic:
#    external: true

volumes:
  cache:
    driver: local
