version: "3"
services:
  api:
    container_name: orantio-api
    build:
      context: .
      target: api
    networks:
      - orantio
    env_file:
      - api/config.env
    environment:
      - GQL_SERVER_URL=http://orantio-apollo:4000/graphql
    ports:
      - "4001:4001"

  apollo:
    container_name: orantio-apollo
    build:
      context: .
      target: apollo
    networks:
      - orantio
    env_file:
      - apollo/config.env
    ports:
      - "4000:4000"

  nginx:
    container_name: orantio-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
      - ./entrypoint.sh:/docker-entrypoint.d/entrypoint.sh
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "80:80"
    networks:
      - orantio
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    entrypoint: ["/bin/sh", "-c"]
    command:
      [
        "/wait-for-it.sh api:4001 apollo:4000 -- /docker-entrypoint.d/entrypoint.sh",
      ]
    depends_on:
      - api
      - apollo

networks:
  orantio:
