version: '3'
services:
  api:
    build: ./api
    networks:
      - backend
    volumes:
      - ./api:/app
    command: npm start
    depends_on:
      - apollo
    environment:
      - GQL_SERVER_URL=http://apollo:4000/graphql
      - NODE_ENV=${ENVIRONMENT}

  apollo:
    build: ./apollo
    networks:
      - backend
    volumes:
      - ./apollo:/app
    command: npm start
    environment:
      - NODE_ENV=${ENVIRONMENT}

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
      - ./entrypoint.sh:/docker-entrypoint.d/entrypoint.sh
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "80:80"
    networks:
      - backend
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "/wait-for-it.sh api:4001 apollo:4000 -- /docker-entrypoint.d/entrypoint.sh" ]
    depends_on:
      - api
      - apollo

networks:
  backend:
