name: "orantio-backend"
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/api.log
    fields:
      service: orantio-api
      log_type: orantio-api
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/apollo.log
    fields:
      service: orantio-apollo
      log_type: orantio-apollo
    fields_under_root: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  index: "filebeat-%{[log_type]}-%{+yyyy.MM.dd}"
  ssl.verification_mode: "none"

setup.kibana:
  host: "https://localhost:5601"