name: build
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "CONTRIBUTING.md"
      - "CODE_OF_CONDUCT.md"
      - "LICENSE"
      - "docs/**"
jobs:
  lint-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier
        run: pnpm prettier

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare config.env
        run: |
          cp api/config.env.template api/config.env
          cp apollo/config.env.template apollo/config.env

      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=2.11.2
          sudo curl -L "https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker Compose services
        run: docker-compose build
